name: 'GHA Parameter test'
description: 'A Custom action'
inputs:
  flag_one:
    description: "a boolean flag"
    default: 'true'
  flag_two:
    description: "a boolean flag"
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Checks flag_one
      if: inputs.flag_one != 'true'
      shell: bash
      env:
        FLAG_ONE: ${{ inputs.flag_one }}
      run: |
        echo "$FLAG_ONE"

    - name: Show flags
      shell: bash
      env:
        FLAG_ONE: ${{ inputs.flag_one }}
        FLAG_TWO: ${{ inputs.flag_two }}
      run: |
        echo "$FLAG_ONE"
        echo "$FLAG_TWO"
